### ISSUE TITLE
a No module name error when docker compose up

### ISSUE THREAD

**Issue by binlyliu** [ddPn08/Radiata#10]
here a error when i run `docker compose up`:

`root@iZ0xii2xgmjh3fqic4wbsjZ:~/Lsmith# docker compose up
[+] Running 1/0
 ⠿ Container lsmith-lsmith-1  Created                                                                                                                                                                                                       0.0s
Attaching to lsmith-lsmith-1
lsmith-lsmith-1  | Installing requirements
lsmith-lsmith-1  | Traceback (most recent call last):
lsmith-lsmith-1  |   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
lsmith-lsmith-1  |     return _run_code(code, main_globals, None,
lsmith-lsmith-1  |   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
lsmith-lsmith-1  |     exec(code, run_globals)
lsmith-lsmith-1  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/__main__.py", line 4, in <module>
lsmith-lsmith-1  |     uvicorn.main()
lsmith-lsmith-1  |   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
lsmith-lsmith-1  |     return self.main(*args, **kwargs)
lsmith-lsmith-1  |   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
lsmith-lsmith-1  |     rv = self.invoke(ctx)
lsmith-lsmith-1  |   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
lsmith-lsmith-1  |     return ctx.invoke(self.callback, **ctx.params)
lsmith-lsmith-1  |   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
lsmith-lsmith-1  |     return __callback(*args, **kwargs)
lsmith-lsmith-1  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/main.py", line 404, in main
lsmith-lsmith-1  |     run(
lsmith-lsmith-1  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/main.py", line 569, in run
lsmith-lsmith-1  |     server.run()
lsmith-lsmith-1  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 60, in run
lsmith-lsmith-1  |     return asyncio.run(self.serve(sockets=sockets))
lsmith-lsmith-1  |   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
lsmith-lsmith-1  |     return loop.run_until_complete(main)
lsmith-lsmith-1  |   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
lsmith-lsmith-1  |     return future.result()
lsmith-lsmith-1  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 67, in serve
lsmith-lsmith-1  |     config.load()
lsmith-lsmith-1  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/config.py", line 477, in load
lsmith-lsmith-1  |     self.loaded_app = import_from_string(self.app)
lsmith-lsmith-1  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/importer.py", line 24, in import_from_string
lsmith-lsmith-1  |     raise exc from None
lsmith-lsmith-1  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/importer.py", line 21, in import_from_string
lsmith-lsmith-1  |     module = importlib.import_module(module_str)
lsmith-lsmith-1  |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
lsmith-lsmith-1  |     return _bootstrap._gcd_import(name[level:], package, level)
lsmith-lsmith-1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
lsmith-lsmith-1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
lsmith-lsmith-1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
lsmith-lsmith-1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
lsmith-lsmith-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
lsmith-lsmith-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
lsmith-lsmith-1  |   File "/app/./modules/main.py", line 10, in <module>
lsmith-lsmith-1  |     from . import config, runner, shared
lsmith-lsmith-1  |   File "/app/./modules/runner.py", line 6, in <module>
lsmith-lsmith-1  |     from .diffusion.tensorrt.inference import TensorRTDiffusionRunner
lsmith-lsmith-1  |   File "/app/./modules/diffusion/tensorrt/inference.py", line 22, in <module>
lsmith-lsmith-1  |     from .clip import create_clip_engine
lsmith-lsmith-1  |   File "/app/./modules/diffusion/tensorrt/clip.py", line 5, in <module>
lsmith-lsmith-1  |     from .engine import build_engine
lsmith-lsmith-1  |   File "/app/./modules/diffusion/tensorrt/engine.py", line 11, in <module>
lsmith-lsmith-1  |     from .models import VAE, UNet
lsmith-lsmith-1  |   File "/app/./modules/diffusion/tensorrt/models.py", line 2, in <module>
lsmith-lsmith-1  |     from submodules.diffusers_0_7_2.src.diffusers.models import (
lsmith-lsmith-1  | ModuleNotFoundError: No module named 'submodules.diffusers_0_7_2.src'
lsmith-lsmith-1 exited with code 0`

my system: ubuntu20.04

**Comment by ddPn08** [comment]
After cloning run the following command to initialize the submodule.
```sh
cd Lsmith
git submodule update --init --recursive
```

**Comment by binlyliu** [comment]
> After cloning run the following command to initialize the submodule.
> 
> ```shell
> cd Lsmith
> git submodule update --init --recursive
> ```

thanks for reply，i was run this command，but same error occur：
`
root@iZ0xii2xgmjh3fqic4wbsjZ:~/Lsmith# git submodule update --init --recursive
Submodule 'submodules/diffusers_0_7_2' (https://github.com/huggingface/diffusers.git) registered for path 'submodules/diffusers_0_7_2'
Cloning into '/root/Lsmith/submodules/diffusers_0_7_2'...
Submodule path 'submodules/diffusers_0_7_2': checked out '91592ed2a88f93b3b29f11020be351dd1f9d21ef'
root@iZ0xii2xgmjh3fqic4wbsjZ:~/Lsmith# docker compose up
[+] Running 1/0
 ⠿ Container lsmith-lsmith-1  Created                                                                                          0.0s
Attaching to lsmith-lsmith-1
lsmith-lsmith-1  | Installing requirements
lsmith-lsmith-1  | Traceback (most recent call last):
lsmith-lsmith-1  |   File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
lsmith-lsmith-1  |     return _run_code(code, main_globals, None,
lsmith-lsmith-1  |   File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
lsmith-lsmith-1  |     exec(code, run_globals)
lsmith-lsmith-1  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/__main__.py", line 4, in <module>
lsmith-lsmith-1  |     uvicorn.main()
lsmith-lsmith-1  |   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
lsmith-lsmith-1  |     return self.main(*args, **kwargs)
lsmith-lsmith-1  |   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
lsmith-lsmith-1  |     rv = self.invoke(ctx)
lsmith-lsmith-1  |   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
lsmith-lsmith-1  |     return ctx.invoke(self.callback, **ctx.params)
lsmith-lsmith-1  |   File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
lsmith-lsmith-1  |     return __callback(*args, **kwargs)
lsmith-lsmith-1  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/main.py", line 404, in main
lsmith-lsmith-1  |     run(
lsmith-lsmith-1  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/main.py", line 569, in run
lsmith-lsmith-1  |     server.run()
lsmith-lsmith-1  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 60, in run
lsmith-lsmith-1  |     return asyncio.run(self.serve(sockets=sockets))
lsmith-lsmith-1  |   File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
lsmith-lsmith-1  |     return loop.run_until_complete(main)
lsmith-lsmith-1  |   File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
lsmith-lsmith-1  |     return future.result()
lsmith-lsmith-1  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/server.py", line 67, in serve
lsmith-lsmith-1  |     config.load()
lsmith-lsmith-1  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/config.py", line 477, in load
lsmith-lsmith-1  |     self.loaded_app = import_from_string(self.app)
lsmith-lsmith-1  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/importer.py", line 24, in import_from_string
lsmith-lsmith-1  |     raise exc from None
lsmith-lsmith-1  |   File "/usr/local/lib/python3.10/dist-packages/uvicorn/importer.py", line 21, in import_from_string
lsmith-lsmith-1  |     module = importlib.import_module(module_str)
lsmith-lsmith-1  |   File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
lsmith-lsmith-1  |     return _bootstrap._gcd_import(name[level:], package, level)
lsmith-lsmith-1  |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
lsmith-lsmith-1  |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
lsmith-lsmith-1  |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
lsmith-lsmith-1  |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
lsmith-lsmith-1  |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
lsmith-lsmith-1  |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
lsmith-lsmith-1  |   File "/app/./modules/main.py", line 10, in <module>
lsmith-lsmith-1  |     from . import config, runner, shared
lsmith-lsmith-1  |   File "/app/./modules/runner.py", line 6, in <module>
lsmith-lsmith-1  |     from .diffusion.tensorrt.inference import TensorRTDiffusionRunner
lsmith-lsmith-1  |   File "/app/./modules/diffusion/tensorrt/inference.py", line 22, in <module>
lsmith-lsmith-1  |     from .clip import create_clip_engine
lsmith-lsmith-1  |   File "/app/./modules/diffusion/tensorrt/clip.py", line 5, in <module>
lsmith-lsmith-1  |     from .engine import build_engine
lsmith-lsmith-1  |   File "/app/./modules/diffusion/tensorrt/engine.py", line 11, in <module>
lsmith-lsmith-1  |     from .models import VAE, UNet
lsmith-lsmith-1  |   File "/app/./modules/diffusion/tensorrt/models.py", line 2, in <module>
lsmith-lsmith-1  |     from submodules.diffusers_0_7_2.src.diffusers.models import (
lsmith-lsmith-1  | ModuleNotFoundError: No module named 'submodules.diffusers_0_7_2.src'
lsmith-lsmith-1 exited with code 0
`

**Comment by ddPn08** [comment]
```
docker compose up --build
```
Please try again with the above command.

**Comment by ddPn08** [comment]
Closing this issue as the project has been significantly updated. Please reopen if you still have problems.
