### ISSUE TITLE
Fresh installs fail due to Pydantic

### ISSUE THREAD

**Issue by 78Alpha** [ddPn08/Radiata#101]
### Describe the bug

Running launch-user.bat for a fresh install after commit bc00bf2de9a24aa75a15f24f6b74a0c6b6cf81f2 does not succeed. Hits a Pydantic error and fails.

After testing other versions, it appears to present in nearly all versions. But it changes where it pops up per version.

### Reproduction

git clone https://github.com/ddPn08/Radiata.git
cd Radiata
./launch-user.bat

If commit is beyond bc00bf2de9a24aa75a15f24f6b74a0c6b6cf81f2 it will fail.

### Expected behavior

WebUI launches and allows for interaction

### System Info

Python 3.10
Windows 11
Versions: 9403f4a0efd6b34f09717e84f4e8c998be43a418, fcdf5d97441459a30ff951cf442a270be850ed02, a32b7b2680da5b7584c60b7159186bc891b900f5, 7f6f2427e9a121c2b751da1e2c9b671588b3b836, bc00bf2de9a24aa75a15f24f6b74a0c6b6cf81f2
RAM: 48 GB
GPU: RTX 3090

### Validations

- [X] Read the [docs](https://ddPn08.github.io/Radiata/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by fa0311** [comment]
The error details are incomplete.
Please paste all of the actual log output.
Or #102 may resolve the issue.

**Comment by ddPn08** [comment]
Merged #102. Try updating and starting again.

**Comment by 78Alpha** [comment]
Issue is resolved after updating. Other errors are in relation to the tensorrt library so I won't bring them up here.
