### ISSUE TITLE
win11でのモデル変換の際にエラー

### ISSUE THREAD

**Issue by koukei46124** [ddPn08/Radiata#25]
win11でモデル変換した際に、恐らく最後の部分でエラーが出て止まってしまいます。
同一のモデルをDocker版では変換できています。
環境は、node.js バージョン18
pnpm
python 3.10.10
pip
CUDA 11.7
cuDNN 8.6.0
TensorRT 8.5
です。
環境構築の際はエラーは有りませんでした。![SnapCrab_NoName_2023-2-8_21-20-32_No-00.png](https://user-images.githubusercontent.com/78602544/217694754-fc0a8d7e-4d82-4069-8596-059e27614910.png)

**Comment by fkunn1326** [comment]
`Unable to load library: nvinfer_builder_resource.dll`
というエラーが出ていますが、tensorrtディレクトリにnvinfer_builder_resource.dllは存在しますか？

**Comment by koukei46124** [comment]
tensorrtディレクトリとは、パスを通したC:\TensorRT-8.5.1.7\lib
で合ってますでしょうか？
どうやらあるようです。
![SnapCrab_NoName_2023-2-9_18-33-13_No-00](https://user-images.githubusercontent.com/78602544/217773823-f11e2995-f4b0-46b5-9c3a-c3e98eb84a51.png)
![SnapCrab_NoName_2023-2-9_18-32-32_No-00](https://user-images.githubusercontent.com/78602544/217773996-bbb7d1ba-83da-44f3-99da-947e588c826c.png)

**Comment by fkunn1326** [comment]
そうなんですね...
とりあえずLsmithのTensorRT推奨バージョンは8.5.3.1(8.5 update2)なので、一回バージョン上げてもらっていいですか？

**Comment by koukei46124** [comment]
上げて再起動してみましたが、状況は変わらないようです…

![SnapCrab_NoName_2023-2-9_20-20-2_No-00](https://user-images.githubusercontent.com/78602544/217798852-1750db5a-85e4-4876-931f-e1a6aaf5b23b.png)

**Comment by fkunn1326** [comment]
https://github.com/NVIDIA/TensorRT/issues/2218
https://github.com/wang-xinyu/tensorrtx/issues/1205

似たようなエラーはありますが正直解決方法はわからないですね... 
`nvinfer_builder_resource.dll` が見つからないのかな...?
`where.exe nvinfer_builder_resource.dll`
としてみてください...

**Comment by koukei46124** [comment]
それもやってみましたが、パスは問題なさそうなんですよね…
しばらくはDocker版で行きますので大丈夫です
お手数おかけしました
![SnapCrab_NoName_2023-2-9_20-38-23_No-00](https://user-images.githubusercontent.com/78602544/217802769-3b01ac1f-55ed-4189-aab4-c6bdebb1aba1.png)

**Comment by ddPn08** [comment]
とりあえず直るまではオープンで

**Comment by ddPn08** [comment]
みすった

**Comment by koukei46124** [comment]
ご報告
何故か、Lsmith\modules\diffusion\tensorrt\engine.pyの
import os
の下に
os.add_dll_directory("C:\TensorRT-8.5.3.1\lib") 
を追加したら動きました。
https://github.com/tensorflow/tensorflow/issues/43193
どうやら一部環境でwhereでは読めるのにpython上では環境変数を読み取れないバグか何かがある模様です。
対処療法過ぎるし人によってパスが違うので、
import osから、環境変数を取得してos.add_dll_directoryを動かすような処理をすれば
解決するような気もしますが、一部の人のおまかんな気もします…
![SnapCrab_NoName_2023-2-20_22-50-22_No-00](https://user-images.githubusercontent.com/78602544/220125875-1e58a357-4564-4e4b-a615-7e040800bd5d.png)
