### ISSUE TITLE
win10、dockerよりengine build すると「 libcublasLt.so.12が見つからない。」とエラー。

### ISSUE THREAD

**Issue by tekitou898009890** [ddPn08/Radiata#29]
ビルドはfull,light両方試しましたが同じ結果になりました。

lsmith-lsmith-1  | Exporting model: models/WarriorMama777/AbyssOrangeMix2/onnx/unet.onnx
Downloading (…)_pytorch_model.bin";: 100%|██████████| 3.44G/3.44G [05:47<00:00, 9.91MB/s]
Downloading (…)ain/unet/config.json: 100%|██████████| 1.02k/1.02k [00:00<00:00, 421kB/s]
lsmith-lsmith-1  | The config attributes {'class_embed_type': None, 'dual_cross_attention': False, 'mid_block_type': 'UNetMidBlock2DCrossAttn', 'num_class_embeds': None, 'only_cross_attention': False, 'resnet_time_scale_shift': 'default', 'upcast_attention': False, 'use_linear_projection': False} were passed to UNet2DConditionModel, but are not expected and will be ignored. Please verify your config.json configuration file.
lsmith-lsmith-1  | /app/./submodules/diffusers_0_7_2/src/diffusers/models/unet_2d_condition.py:273: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
lsmith-lsmith-1  |   if any(s % default_overall_up_factor != 0 for s in sample.shape[-2:]):
lsmith-lsmith-1  | Could not load library libcublasLt.so.12. Error: libcublasLt.so.12: cannot open shared object file: No such file or directory

**Comment by mssmison** [comment]
Also having this issue, windows 11 docker

**Comment by tekitou898009890** [comment]
It is assumed that cuda-toolkit12.0 is installed by some command and libcublasLt.so.12 is called at runtime from there.

Therefore, I think it would be better to install the toolkit beforehand as a way to solve this problem.

どこかのコマンドでcuda-toolkit12.0がインストールされていて、そこから実行時にlibcublasLt.so.12を呼び出していると思われます。

故に解決する方法として、事前にtoolkitを導入したほうがいいと考えますがどうでしょう。

**Comment by ddPn08** [comment]
I tried downgrading cuda-python to 11.8, but it doesn't seem to change. . .

cuda-pythonを11.8に落としてみましたが変わらないようです。。。

**Comment by ddPn08** [comment]
Probably fixed.

**Comment by modulman** [comment]
If you see it error on Ubuntu 22.04, jost add to launch-user.sh file this two lines:
```
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/Lsmith/venv/lib/python3.10/site-packages/torch/lib/
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/Lsmith/venv/lib/python3.10/site-packages/tensorrt/
```

next step just run launch-user.sh file:
`bash launch-user.sh`

**Comment by ddPn08** [comment]
Closing this issue as the project has been significantly updated. Please reopen if you still have problems.
