### ISSUE TITLE
Upload to dockerhub?

### ISSUE THREAD

**Issue by Starlento** [ddPn08/Radiata#32]
It always takes my effort and wastes bandwidth during the process of seting up proxy and changing the dockerfile to build an image successfully under Chinese network. Actually the proxy is quite complex when it comes to docker build and wsl2.
Could you upload the docker image to dockerhub? I know that the content is updating constantly, but if the environment is fixed, it is easy for others to mount or modify/reinstall the code, which means you do not need to upload every version to dockerhub.

**Comment by ddPn08** [comment]
Closing this issue as the project has been significantly updated. Please reopen if you still have problems.
