### ISSUE TITLE
Error when Model build

### ISSUE THREAD

**Issue by tricksterzero** [ddPn08/Radiata#48]
### Describe the bug

モデルのビルドが失敗します。

- andite/pastel-mix
- CompVis/stable-diffusion-v1-4

の2モデルで試しましたがどちらも以下のようなエラーを出して終了してしまいます。
Denoising precision(float16/32)両方で試しましたが同じような終了仕方でした。

![Lsmith_error_02(pastel-mix)](https://user-images.githubusercontent.com/57392053/219272969-8081ddb6-e0eb-4564-9984-1d32820f96b1.png)

### Reproduction

1. Dockerを起動
2. Lsmithを起動
3. ブラウザ(Chrome)からUIにアクセス
4. Engineタブへ移動
5. Model IDを入力
6. Denoising precisionを選択
7. Build
8. エラーで終了

### Expected behavior

モデルのビルドが成功すること。

### System Info

- Windows 10 Home + WSL2
- Docker Desktop for Windows v4.16.3
- GeForce RTX 3060(12GB)
- CPU Ryzen 5 3600
- Memory 16GB

### Validations

- [X] Read the [docs](https://ddPn08.github.io/Lsmith/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by Stax124** [comment]
Can you check if this one compiles?
https://huggingface.co/runwayml/stable-diffusion-v1-5
This seems to me like Docker error code 137 - out of memory - and not a VRAM, just normal RAM

Try closing most of the unnecessary apps and running again, while monitoring RAM with Task Manager

**Comment by tricksterzero** [comment]
不必要な常駐アプリを終了してから
runwayml/stable-diffusion-v1-5
のビルドを試してみました。
結果としては失敗しました。

RAMについては
float32選択時のビルドは使用率97%を超える挙動でした。
float16選択時は使用率79～87%で推移していました。

他に何かできることはあるでしょうか？

![Lsmith_error_03(SD1 5)](https://user-images.githubusercontent.com/57392053/219285845-d083e61b-4a77-454e-b64a-45caf812c841.png)

**Comment by Stax124** [comment]
Cannot help you when you use japanes

**Comment by ddPn08** [comment]
Closing this issue as the project has been significantly updated. Please reopen if you still have problems.
