### ISSUE TITLE
I followed the docker installation and run the container but the URL is not working

### ISSUE THREAD

**Issue by ghost** [ddPn08/Radiata#50]
### Describe the bug

I followed the docker install guide and the container runs, but when I visit http://localhost:8000 it tells me the connection has been refused? Restarting the container did not work. Im trying the windows install guide now. edit: It cant find the command pnpm even though I installed it with pip

### Reproduction

Its in the description

### Expected behavior

Clean install

### System Info

Win 10

### Validations

- [X] Read the [docs](https://ddPn08.github.io/Lsmith/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddPn08** [comment]
I just got rid of the need to build the front end. Please update and try again.

**Comment by corebro** [comment]
When clicking on launch-user.bat my explorer.exe flickers but nothing happens after that

**Comment by Stax124** [comment]
> When clicking on launch-user.bat my explorer.exe flickers but nothing happens after that

Try running it directly from CMD, so that the error persists after it exits, then paste it here

**Comment by corebro** [comment]
I googled but I dont know how to do that. just typing in launch-user.bat didnt work like it would with .sh in linux

**Comment by ddPn08** [comment]
Closing this issue as the project has been significantly updated. Please reopen if you still have problems.
