### ISSUE TITLE
Continuation of this project

### ISSUE THREAD

**Issue by ddPn08** [ddPn08/Radiata#63]
Sorry for the delay in updating for a while.
I was so busy with the university entrance exam that I didn't have time to code.

I would like to talk about the future of this “LSmith”.
TensorRT 8.6 is expected to be released soon, and we plan to release it again at that time.

TensorRT 8.6 is expected to include updates for StableDiffusion 2.1 support and low VRAM stability.

I will add it here again as soon as something is decided, so please wait for a while.

**Comment by ddPn08** [comment]
I am writing code now.
We hope to release a beta version soon.

**Comment by ddPn08** [comment]
https://github.com/ddPn08/Lsmith/commit/4252dd49d72064ace93dab12901fd0aa5933039f

**Comment by zhangvia** [comment]
do you have the plan to add controlnet to this project?

**Comment by ddPn08** [comment]
I'm having a really hard time with lora right now. I'd like to add ControlNet as well, but I'm not sure how.

**Comment by Stax124** [comment]
> I'm having a really hard time with lora right now. I'd like to add ControlNet as well, but I'm not sure how.

We were able to do it with AITemplate, but it needs a different UNet as controlnet has 16 inputs

Ref: https://github.com/VoltaML/voltaML-fast-stable-diffusion/blob/45e9ee721e2cd2b0d80cdfbc072420504e194e73/core/aitemplate/src/compile_lib/compile_controlnet_unet.py#L75-L96

**Comment by zwj536** [comment]
> I'm having a really hard time with lora right now. I'd like to add ControlNet as well, but I'm not sure how.

Hi，how is everything going? Can you share some ideas about supporting for Lora, or what kind of trouble did you encounter

**Comment by ddPn08** [comment]
> Hi，how is everything going? Can you share some ideas about supporting for Lora, or what kind of trouble did you encounter

thank you. For the time being, I decided to give up on implementing lora.

**Comment by ddPn08** [comment]
And now I have created a new webui named Radiata.

[![](https://raw.githubusercontent.com/ddPn08/Radiata/main/docs/images/readme-top.png)](https://github.com/ddPn08/Radiata/)

The server system is almost inherited from Lsmith.
The main changes are the implementation of diffusers and DeepFloyd IF, and the front-end has been changed to gradio.

**Comment by ddPn08** [comment]
@Stax124
Thank you for answering various issues. And sorry for abandoning the project.

**Comment by Stax124** [comment]
> @Stax124 Thank you for answering various issues. And sorry for abandoning the project.

No problem man, feel free to take some of our code if you need a headstart with AITemplate (or other stuff). I will be on Discord as always if you need something and I will try to keep up with you. Good luck.
