### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by zhangvia** [ddPn08/Radiata#67]
![image](https://user-images.githubusercontent.com/38352569/231425723-0a03fede-5121-4fac-9df2-3abe9419a896.png)
i install all dependencies manully,and run the command bash launch.sh --host 0.0.0.0. then this error happens.i have no idea what this error means.the only different thing from the project is i have a tensorrt 8.5.2.2.did i miss some dependencies?

**Comment by Stax124** [comment]
You need Python 3.10, this is normal if you are on Python3.8

**Comment by Stax124** [comment]
You don't need to reinstall, your 3.8 should stay as default interpretor

This might be helpful:
https://computingforgeeks.com/how-to-install-python-on-ubuntu-linux-system/

You will need to call it with /usr/bin/python3.10, not just python3 after you install it (or similar, I am not 100% sure)

**Comment by zhangvia** [comment]
> You don't need to reinstall, your 3.8 should stay as default interpretor
> 
> This might be helpful: https://computingforgeeks.com/how-to-install-python-on-ubuntu-linux-system/
> 
> You will need to call it with /usr/bin/python3.10, not just python3 after you install it (or similar, I am not 100% sure)

thank you! i'll try it later

**Comment by zhangvia** [comment]
> You don't need to reinstall, your 3.8 should stay as default interpretor
> 
> This might be helpful: https://computingforgeeks.com/how-to-install-python-on-ubuntu-linux-system/
> 
> You will need to call it with /usr/bin/python3.10, not just python3 after you install it (or similar, I am not 100% sure)

i install the python3.10 and it work! but when i convert the model to tensort engine,i got cuda out of memory. an i want to change the gpu from 0 to 2,because i have four gpu. i use the CUDA_VISIBLE_DEVICES=2, but it didn't work. the app still run on gpu 0. how can i choose which gpu to use?

**Comment by zhangvia** [comment]
> You don't need to reinstall, your 3.8 should stay as default interpretor
> 
> This might be helpful: https://computingforgeeks.com/how-to-install-python-on-ubuntu-linux-system/
> 
> You will need to call it with /usr/bin/python3.10, not just python3 after you install it (or similar, I am not 100% sure)

i install the python3.10,and it worked! but when i use the engine generator, i got this error
![image](https://user-images.githubusercontent.com/38352569/231454485-72169161-285d-463b-9342-9690a97de4d3.png)
![image](https://user-images.githubusercontent.com/38352569/231454567-6212e6c1-9d83-4ad7-8a2d-2b1333fd5ba5.png)
in the model dir of engine tab, i use the local model path. because i've downloaded the runway/stable-diffusion-v1-5 already.
and i saw the onnx model,it converted the .bin to .onnx successfully.but when it build the tensorrt engine,loading network from onnx model went wrong.and the error info seems like the image size is smaller than the filter,which is definitly wrong.why would this happen.i didn't change any code, can't it process the stable diffusion 1.5?

**Comment by Stax124** [comment]
I think that Lsmith had support only for diffuser models, but I might be wrong here. I followed the changes about a month and a half ago, but now I do not have time for it (I am maintaining Volta) - so this is probably as far as I can get you through.

@ddPn08 can you please follow up here?

**Comment by Stax124** [comment]
Yeah, that was what I meant, this might be something in the code or configuration. Maybe try running it with Docker and check if it can run there.

**Comment by zhangvia** [comment]
> Yeah, that was what I meant, this might be something in the code or configuration. Maybe try running it with Docker and check if it can run there.

sorry,i've tried the docker.i use cluster to run this project.maybe some configuration of the cluster went wrong,my daemon docker service couldn't start,so i can't use docker now.tomorrow i will comunicate with the maintenance staff of the cluster and try docker again.but i still want to know why this error happen.

**Comment by ddPn08** [comment]
Closing this issue as the project has been significantly updated. Please reopen if you still have problems.
