### ISSUE TITLE
Issue: TensorRT is available, but torch version is not compatible.

### ISSUE THREAD

**Issue by Em1tSan** [ddPn08/Radiata#69]
### Describe the bug

When you run with --tensorrt, it installs and then a line appears in the terminal:
TensorRT is available, but torch version is not compatible.

```
################################################################
Launching launch.py...
################################################################
Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]
Commit hash: 36ffe3ae02d7ec023cfc394b59dc82b6848a4e5d
Installing requirements
Installing tensorrt requirements
TensorRT version: 8.6.0
TensorRT is available, but torch version is not compatible.
Loading runwayml/stable-diffusion-v1-5...
```

```
venv "E:\SD\Radiata\venv\Scripts\Python.exe"
Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Commit hash: 88aaee19a955403cdf0b428550c0ffaee2ccdec9
Installing requirements
Installing tensorrt requirements
Installing tensorrt
A matching Triton is not available, some optimizations will not be enabled.
Error caught was: No module named 'triton'
TensorRT version: 8.6.0
TensorRT is available, but torch version is not compatible.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
```

The error is on both Windows 11 and Ubuntu 22.04.

### Reproduction

Start ./launch.sh --tensorrt
or
launch-user.bat with 
set COMMANDLINE_ARGS= --tensorrt

### Expected behavior

Works of tensorrt

### System Info

Python 3.10
OS: Windows 11
Ubuntu 22.04 WSL2

### Validations

- [X] Read the [docs](https://ddPn08.github.io/Lsmith/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddPn08** [comment]
I just updated the documentation. Have a look at this. https://ddpn08.github.io/Radiata/en/usage/tensorrt.html
pytorch version must be less than 2.
