### ISSUE TITLE
xformers version conflict

### ISSUE THREAD

**Issue by 34292885** [ddPn08/Radiata#70]
### Describe the bug

Since xformers installed by default doesn't seem to specify a version, the latest version requires PyTorch 2.0.0, which may conflict with the version of the documentation TensorRT heading

### Reproduction

As Document Usage TensorRT
Windows
Rewrite webui-user.bat as follows
bat
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS=--tensorrt --reinstall-torch
set TORCH_COMMAND=pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 --extra-index-url https://download.pytorch.org/whl/cu117

call launch.bat
Run launch-user.bat

### Expected behavior

install and run properly

### System Info

python3.10

### Validations

- [X] Read the [docs](https://ddPn08.github.io/Lsmith/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddPn08** [comment]
Corrected some documents and code.
If you need torch version less than 2, you need to set xformers version to 0.0.16.
https://ddpn08.github.io/Radiata/en/usage/tensorrt.html

**Comment by ddPn08** [comment]
Changed the default installed version of torch to 1.13.1 to avoid confusion.
