### ISSUE TITLE
nvinfer error when converting models to tensorrt

### ISSUE THREAD

**Issue by boricuapab** [ddPn08/Radiata#95]
### Describe the bug

I'm able to convert models to tensorrt versions, but I keep seeing this error.

[E] 2: [virtualMemoryBuffer.cpp::nvinfer1::StdVirtualMemoryBufferImpl::resizePhysical::140] Error Code 2: OutOfMemory (no further information)

### Reproduction

convert model to tensor rt

### Expected behavior

the model conversion to tensor rt works, so I wouldn't expect to see that nvinver error in the conda window

### System Info

WIN 10
rtx 2060 super 8gb

### Additional context

[W] onnx2trt_utils.cpp:374: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[W] onnx2trt_utils.cpp:400: One or more weights outside the range of INT32 was clamped
[I]     Configuring with profiles: [Profile().add('sample', min=(2, 4, 32, 32), opt=(2, 4, 96, 96), max=(2, 4, 128, 128)).add('encoder_hidden_states', min=(2, 77, 768), opt=(2, 77, 768), max=(2, 77, 768)).add('timestep', min=[1], opt=[1], max=[1])]
[I] Building engine with configuration:
    Flags                  | [FP16]
    Engine Capability      | EngineCapability.DEFAULT
    Memory Pools           | [WORKSPACE: 8191.69 MiB, TACTIC_DRAM: 8191.69 MiB]
    Tactic Sources         | []
    Profiling Verbosity    | ProfilingVerbosity.DETAILED
    Preview Features       | [FASTER_DYNAMIC_SHAPES_0805, DISABLE_EXTERNAL_TACTIC_SOURCES_FOR_CORE_0805]
[E] 2: [virtualMemoryBuffer.cpp::nvinfer1::StdVirtualMemoryBufferImpl::resizePhysical::140] Error Code 2: OutOfMemory (no further information)
[W] Requested amount of GPU memory (4294967296 bytes) could not be allocated. There may not be enough free memory for allocation to succeed.
[E] 2: [virtualMemoryBuffer.cpp::nvinfer1::StdVirtualMemoryBufferImpl::resizePhysical::140] Error Code 2: OutOfMemory (no further information)
[E] 2: [virtualMemoryBuffer.cpp::nvinfer1::StdVirtualMemoryBufferImpl::resizePhysical::140] Error Code 2: OutOfMemory (no further information)
[E] 2: [virtualMemoryBuffer.cpp::nvinfer1::StdVirtualMemoryBufferImpl::resizePhysical::140] Error Code 2: OutOfMemory (no further information)
[E] 2: [virtualMemoryBuffer.cpp::nvinfer1::StdVirtualMemoryBufferImpl::resizePhysical::140] Error Code 2: OutOfMemory (no further information)
[W] TensorRT encountered issues when converting weights between types and that could affect accuracy.
[W] If this is not the desired behavior, please modify the weights or retrain with regularization to adjust the magnitude of the weights.
[W] Check verbose logs for the list of affected weights.
[W] - 227 weights are affected by this issue: Detected subnormal FP16 values.
[I] Finished engine building in 1342.849 seconds
[I] Saving engine to models\accelerate\tensorrt\1pt5\revAnimated_v11.safetensors\engine\unet.plan

### Validations

- [X] Read the [docs](https://ddPn08.github.io/Radiata/).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.

**Comment by ddPn08** [comment]
If you have less VRAM then you will see that error.
But it's okay if the build eventually completes.
In this case, the build seems to have completed successfully.

**Comment by boricuapab** [comment]
Yes, Radiata is so awesome.  Been converting a few models today, rev1.1, colorful 2.5, realistic vision 1.3.  Here's a comparison of the speed I got using the same seed for a 512px by 512px image on an rtx 2060 super 8gb gpu.  Take a bit of time to generate the engine models though but that's cause I have to use a batch size of 1 to avoid oom.

512x512

Token indices sequence length is longer than the specified maximum sequence length for this model (102 > 77). Running this sequence through the model will result in indexing errors
[WARNING] Prompt was truncated. Try to shorten the prompt or increase max_embeddings_multiples
  4%|██▉                                                                                | 1/28 [00:00<00:04,  5.75it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
  7%|█████▉                                                                             | 2/28 [00:00<00:03,  6.54it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 11%|████████▉                                                                          | 3/28 [00:00<00:03,  6.89it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 14%|███████████▊                                                                       | 4/28 [00:00<00:03,  7.06it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 18%|██████████████▊                                                                    | 5/28 [00:00<00:03,  7.17it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 21%|█████████████████▊                                                                 | 6/28 [00:00<00:03,  7.19it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 25%|████████████████████▊                                                              | 7/28 [00:00<00:02,  7.23it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 29%|███████████████████████▋                                                           | 8/28 [00:01<00:02,  7.28it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 32%|██████████████████████████▋                                                        | 9/28 [00:01<00:02,  7.37it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 36%|█████████████████████████████▎                                                    | 10/28 [00:01<00:02,  7.37it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 39%|████████████████████████████████▏                                                 | 11/28 [00:01<00:02,  7.31it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 43%|███████████████████████████████████▏                                              | 12/28 [00:01<00:02,  7.29it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 46%|██████████████████████████████████████                                            | 13/28 [00:01<00:02,  7.29it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 50%|█████████████████████████████████████████                                         | 14/28 [00:01<00:01,  7.32it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 54%|███████████████████████████████████████████▉                                      | 15/28 [00:02<00:01,  7.33it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 57%|██████████████████████████████████████████████▊                                   | 16/28 [00:02<00:01,  7.31it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 61%|█████████████████████████████████████████████████▊                                | 17/28 [00:02<00:01,  7.30it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 64%|████████████████████████████████████████████████████▋                             | 18/28 [00:02<00:01,  7.30it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 68%|███████████████████████████████████████████████████████▋                          | 19/28 [00:02<00:01,  7.32it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 71%|██████████████████████████████████████████████████████████▌                       | 20/28 [00:02<00:01,  7.31it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 75%|█████████████████████████████████████████████████████████████▌                    | 21/28 [00:02<00:00,  7.31it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 79%|████████████████████████████████████████████████████████████████▍                 | 22/28 [00:03<00:00,  7.30it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 82%|███████████████████████████████████████████████████████████████████▎              | 23/28 [00:03<00:00,  7.29it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 86%|██████████████████████████████████████████████████████████████████████▎           | 24/28 [00:03<00:00,  7.29it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 89%|█████████████████████████████████████████████████████████████████████████▏        | 25/28 [00:03<00:00,  7.29it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 93%|████████████████████████████████████████████████████████████████████████████▏     | 26/28 [00:03<00:00,  7.28it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 96%|███████████████████████████████████████████████████████████████████████████████   | 27/28 [00:03<00:00,  7.28it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:03<00:00,  7.24it/s]

Loading TensorRT engine: models\accelerate\tensorrt\1pt5\colorful_v25.safetensors\engine\unet.plan
[I] Loading bytes from models\accelerate\tensorrt\1pt5\colorful_v25.safetensors\engine\unet.plan
[INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
[INFO] HTTP Request: POST http://127.0.0.1:7860/reset "HTTP/1.1 200 OK"
[INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
Token indices sequence length is longer than the specified maximum sequence length for this model (102 > 77). Running this sequence through the model will result in indexing errors
[WARNING] Prompt was truncated. Try to shorten the prompt or increase max_embeddings_multiples
  4%|██▉                                                                                | 1/28 [00:00<00:03,  7.93it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
[INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 11%|████████▉                                                                          | 3/28 [00:00<00:02,  9.70it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
[INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 18%|██████████████▊                                                                    | 5/28 [00:00<00:02, 10.43it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
[INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 25%|████████████████████▊                                                              | 7/28 [00:00<00:01, 10.78it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
[INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 32%|██████████████████████████▋                                                        | 9/28 [00:00<00:01, 10.95it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
[INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 39%|████████████████████████████████▏                                                 | 11/28 [00:01<00:01, 11.00it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
[INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 46%|██████████████████████████████████████                                            | 13/28 [00:01<00:01, 11.03it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
[INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 54%|███████████████████████████████████████████▉                                      | 15/28 [00:01<00:01, 11.04it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
[INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 61%|█████████████████████████████████████████████████▊                                | 17/28 [00:01<00:00, 11.00it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
[INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 68%|███████████████████████████████████████████████████████▋                          | 19/28 [00:01<00:00, 11.00it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
[INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 75%|█████████████████████████████████████████████████████████████▌                    | 21/28 [00:01<00:00, 11.03it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
[INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 82%|███████████████████████████████████████████████████████████████████▎              | 23/28 [00:02<00:00, 11.05it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
[INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 89%|█████████████████████████████████████████████████████████████████████████▏        | 25/28 [00:02<00:00, 11.07it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
[INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
 96%|███████████████████████████████████████████████████████████████████████████████   | 27/28 [00:02<00:00, 11.08it/s][INFO] HTTP Request: POST http://127.0.0.1:7860/api/predict "HTTP/1.1 200 OK"
100%|██████████████████████████████████████████████████████████████████████████████████| 28/28 [00:02<00:00, 10.91it/s]
